import ThemeSwitcher from "@/components/themeSwitcher";
import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Employee Dashboard",
  description: "Generated by Masoud Harooni",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fa" dir="ltr">
      <body className={`bg-bgLight dark:bg-bg text-textLight dark:text-text p-5 pr-0`}>
        {children}
        <ThemeSwitcher />
      </body>
    </html>
  );
}
