import ThemeSwitcher from "@/components/themeSwitcher";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Trading Journal",
  description: "Generated by Our team",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`${inter.className} bg-white dark:bg-[#2A3240]`}>
        {children}
        <ThemeSwitcher />
      </body>
    </html>
  );
}
